# Cloudflare migration plan: {{project_name}}

Generated by `snitch-cloudflare` on {{generated_at}}. This is a read-only assessment — nothing has been provisioned. Apply via `snitch-cloudflare.sh fix <area>` after agreeing to the plan.

---

## Verdict

**{{verdict}}** — {{verdict_one_liner}}

> {{verdict_summary}}

## Why

{{why_paragraph}}

{{why_bullets}}

## Stack detected

- **Framework:** {{stack_framework}} ({{stack_framework_version}})
- **Runtime:** {{stack_runtime}}
- **Build output:** {{stack_build_output}}
- **Routing:** {{stack_routing}}
- **Auth:** {{stack_auth}}
- **Other signals:** {{stack_other_signals}}

## Database guidance

**Detected:** {{db_engine}} ({{db_version}}) via {{db_signal}}.

**Recommendation:** {{db_recommendation}}

{{db_details}}

> Connection strings belong in **Workers Secrets** (`wrangler secret put DATABASE_URL`), never in `wrangler.toml` `[vars]`.

## Storage guidance

**Detected:** {{storage_provider}} ({{storage_signal}}).

**Recommendation:** {{storage_recommendation}}

{{storage_details}}

**Estimated egress savings vs S3/GCS/Azure (R2 zero-egress):** {{storage_egress_estimate}}

## Compute guidance

{{compute_paragraph}}

**Problematic dependencies (if any):**
{{compute_problem_deps}}

**Long-running / WebSocket / SSE workloads:**
{{compute_long_running}}

## AI/ML guidance

{{ai_recommendation_block}}

## Cost realism

| Component         | Free tier                  | Estimated monthly @ {{traffic_estimate}} |
|-------------------|----------------------------|------------------------------------------|
| Workers requests  | 100k/day                   | {{cost_workers}}                         |
| Pages             | unlimited static           | {{cost_pages}}                           |
| D1 reads / writes | 5M / 100k per day          | {{cost_d1}}                              |
| R2 storage + ops  | 10 GB + 1M Class A / 10M B | {{cost_r2}}                              |
| Hyperdrive        | included with Workers Paid | {{cost_hyperdrive}}                      |
| Durable Objects   | n/a                        | {{cost_do}}                              |
| AI Gateway        | generous free tier         | {{cost_ai_gateway}}                      |
| Workers AI        | per-neuron                 | {{cost_workers_ai}}                      |

**Bottom line:** {{cost_bottom_line}}

## DNS cutover playbook

1. **Lower TTL.** At your current DNS provider, drop the A/AAAA/CNAME TTL on `{{domain}}` to 60 seconds. Wait at least one previous-TTL period (often 24h) so caches expire.
2. **Orange cloud.** Add `{{domain}}` to Cloudflare, recreate the records, set them to **proxied** (orange cloud). Verify the proxied records resolve from external resolvers (`dig @1.1.1.1 {{domain}}` should return Cloudflare IPs).
3. **Cutover.** Change the registrar nameservers to the two Cloudflare NS records shown in the Cloudflare dashboard. Watch propagation (`whois {{domain}}` + `dig NS {{domain}}`).
4. **Verify.** Confirm: HTTPS works (`curl -vI https://{{domain}}`), the WAF events page records traffic, edge cert is provisioned, no `525`/`526`/`520` errors, origin only receives traffic via Cloudflare IPs (configure origin firewall — see `origin-hardening.checklist.md`).

## Rollback path

If anything looks wrong within the first 24 hours:

1. Revert the registrar nameservers to the previous provider's NS records.
2. Wait the new TTL (60s) for caches to clear; longer at upstream resolvers.
3. Confirm traffic is back on the old origin (`curl -vI https://{{domain}}`).
4. Keep the Cloudflare zone in place — no need to delete; it's harmless once the NS is reverted.

A snapshot of pre-cutover state was written to `~/.claude/skills/snitch-cloudflare/.state/migration-pre-cutover-{{snapshot_id}}.json` for diffing later.

## Sources cited

{{sources}}
