# Cloudflare Terraform skeleton.
# Generated by `snitch-cloudflare terraform`. Replace {{placeholders}} before applying.
# Provider docs: https://registry.terraform.io/providers/cloudflare/cloudflare/latest/docs

terraform {
  required_version = ">= 1.5.0"
  required_providers {
    cloudflare = {
      source  = "cloudflare/cloudflare"
      version = "~> 4.0"
    }
  }
  # Recommended: store state remotely. Pick one.
  # backend "s3"     { bucket = "..." key = "cloudflare/{{zone_name}}.tfstate" region = "us-east-1" encrypt = true }
  # backend "remote" { organization = "{{tf_org}}" workspaces { name = "cloudflare-{{zone_name}}" } }
}

# -----------------------------------------------------------------------------
# Inputs. Set via:
#   - Environment: CLOUDFLARE_API_TOKEN, TF_VAR_account_id, TF_VAR_zone_id
#   - tfvars file (DO NOT commit it)
#   - CI secret variables
# -----------------------------------------------------------------------------
variable "cloudflare_api_token" {
  description = "Scoped Cloudflare API token. Use the minimum scopes from token-permissions.checklist.md."
  type        = string
  sensitive   = true
}

variable "account_id" {
  description = "Cloudflare account ID. Find via `bash snitch-cloudflare.sh check` or the dashboard."
  type        = string
}

variable "zone_id" {
  description = "Cloudflare zone ID for {{zone_name}}."
  type        = string
}

variable "zone_name" {
  description = "The apex domain name (e.g., example.com)."
  type        = string
  default     = "{{zone_name}}"
}

provider "cloudflare" {
  api_token = var.cloudflare_api_token
}

# -----------------------------------------------------------------------------
# Zone-wide settings. The `cloudflare_zone_settings_override` resource is the
# Terraform equivalent of the Cloudflare dashboard's SSL/TLS + Security tabs.
# -----------------------------------------------------------------------------
resource "cloudflare_zone_settings_override" "{{zone_resource_name}}" {
  zone_id = var.zone_id

  settings {
    ssl                      = "strict"          # Full (Strict): origin must present a valid cert.
    min_tls_version          = "1.2"
    tls_1_3                  = "on"
    always_use_https         = "on"
    automatic_https_rewrites = "on"
    opportunistic_encryption = "on"
    universal_ssl            = "on"
    http3                    = "on"
    zero_rtt                 = "on"
    ipv6                     = "on"
    websockets               = "on"
    brotli                   = "on"
    early_hints              = "on"

    # Security
    security_level   = "medium"                  # under_attack only during incidents.
    challenge_ttl    = 1800
    browser_check    = "on"
    privacy_pass     = "on"
    server_side_exclude = "on"

    # HSTS — enforce + preload after stability.
    security_header {
      enabled            = true
      preload            = true
      max_age            = 31536000
      include_subdomains = true
      nosniff            = true
    }
  }
}

# -----------------------------------------------------------------------------
# Example DNS record. Add one resource per record. Proxied = orange cloud.
# -----------------------------------------------------------------------------
resource "cloudflare_record" "apex_a" {
  zone_id = var.zone_id
  name    = "@"
  type    = "A"
  value   = "{{origin_ip}}"
  ttl     = 1                                    # 1 = auto.
  proxied = true                                 # ALWAYS proxy unless email/SMTP record.
  comment = "Managed by Terraform via snitch-cloudflare"
}

resource "cloudflare_record" "www_cname" {
  zone_id = var.zone_id
  name    = "www"
  type    = "CNAME"
  value   = var.zone_name
  ttl     = 1
  proxied = true
  comment = "Managed by Terraform via snitch-cloudflare"
}

# -----------------------------------------------------------------------------
# WAF custom rule — foreign-tech path block.
# Generated from templates/waf-foreign-tech.starter.json. Re-generate after
# changing detected stack.
# -----------------------------------------------------------------------------
resource "cloudflare_ruleset" "{{zone_resource_name}}_custom" {
  zone_id     = var.zone_id
  name        = "snitch-cloudflare custom rules"
  description = "Managed by snitch-cloudflare"
  kind        = "zone"
  phase       = "http_request_firewall_custom"

  rules {
    description = "cloudflare-secure:foreign-tech-paths"
    action      = "block"
    expression  = <<-EOT
      {{foreign_tech_expression}}
    EOT
    enabled     = true
  }

  rules {
    description = "cloudflare-secure:block-known-bad-UAs"
    action      = "block"
    expression  = <<-EOT
      {{bad_ua_expression}}
    EOT
    enabled     = true
  }
}

# -----------------------------------------------------------------------------
# Rate limit on auth endpoints.
# -----------------------------------------------------------------------------
resource "cloudflare_ruleset" "{{zone_resource_name}}_ratelimit" {
  zone_id     = var.zone_id
  name        = "snitch-cloudflare rate limits"
  description = "Managed by snitch-cloudflare"
  kind        = "zone"
  phase       = "http_ratelimit"

  rules {
    description = "cloudflare-secure:rate-limit-auth"
    action      = "managed_challenge"
    expression  = "(http.request.method eq \"POST\") and ((http.request.uri.path eq \"/login\") or (http.request.uri.path eq \"/signup\") or (starts_with(http.request.uri.path, \"/api/auth/\")))"
    enabled     = true

    ratelimit {
      characteristics       = ["ip.src"]
      period                = 60
      requests_per_period   = 5
      mitigation_timeout    = 600
    }
  }
}

# -----------------------------------------------------------------------------
# Transform rule — security headers on every response.
# -----------------------------------------------------------------------------
resource "cloudflare_ruleset" "{{zone_resource_name}}_security_headers" {
  zone_id     = var.zone_id
  name        = "snitch-cloudflare security headers"
  description = "Managed by snitch-cloudflare"
  kind        = "zone"
  phase       = "http_response_headers_transform"

  rules {
    description = "cloudflare-secure:security-headers"
    action      = "rewrite"
    expression  = "(true)"
    enabled     = true

    action_parameters {
      headers {
        name      = "Strict-Transport-Security"
        operation = "set"
        value     = "max-age=31536000; includeSubDomains; preload"
      }
      headers {
        name      = "X-Content-Type-Options"
        operation = "set"
        value     = "nosniff"
      }
      headers {
        name      = "X-Frame-Options"
        operation = "set"
        value     = "DENY"
      }
      headers {
        name      = "Referrer-Policy"
        operation = "set"
        value     = "strict-origin-when-cross-origin"
      }
      headers {
        name      = "Permissions-Policy"
        operation = "set"
        value     = "geolocation=(), microphone=(), camera=(), payment=()"
      }
      headers {
        name      = "Cross-Origin-Opener-Policy"
        operation = "set"
        value     = "same-origin"
      }
      headers {
        name      = "Cross-Origin-Resource-Policy"
        operation = "set"
        value     = "same-site"
      }
      headers {
        name      = "Server"
        operation = "remove"
      }
      headers {
        name      = "X-Powered-By"
        operation = "remove"
      }
    }
  }
}

# -----------------------------------------------------------------------------
# DNSSEC — enable at the zone, then add the DS at your registrar.
# -----------------------------------------------------------------------------
# resource "cloudflare_zone_dnssec" "{{zone_resource_name}}" {
#   zone_id = var.zone_id
# }
