# lib/terraform.sh — emit Terraform HCL for current DigitalOcean state.
# Read-only. Pins the digitalocean/digitalocean provider; emits Droplets,
# domains, firewalls, and load balancers as a starting point.
#
# Exports: run_terraform

_tf_sanitize_name() {
  printf '%s' "$1" \
    | tr '[:upper:]' '[:lower:]' \
    | sed -E 's/[^a-z0-9]+/_/g; s/^_+//; s/_+$//; s/^$/x/'
}

_tf_emit_header() {
  cat <<'EOF'
# Auto-generated by snitch-digitalocean. Read-only export of current state.
# Provider version pinned because schema changes between major versions.

terraform {
  required_providers {
    digitalocean = {
      source  = "digitalocean/digitalocean"
      version = "~> 2.0"
    }
  }
}

provider "digitalocean" {
  # token is read from DIGITALOCEAN_ACCESS_TOKEN by default.
}
EOF
}

_tf_emit_droplets() {
  local body
  body="$(do_get /droplets?per_page=200 2>/dev/null)" || return 0
  printf '\n# Droplets.\n'
  jq -r '.droplets[]? | [.id, .name, (.size_slug // ""), (.region.slug // ""), (.image.slug // .image.distribution // "")] | @tsv' <<<"$body" \
    | while IFS=$'\t' read -r did dname dsize dregion dimage; do
        [[ -z "$did" ]] && continue
        local ln; ln="$(_tf_sanitize_name "${dname}")"
        printf 'resource "digitalocean_droplet" "%s" {\n' "$ln"
        printf '  name   = "%s"\n' "$dname"
        printf '  size   = "%s"\n' "${dsize:-s-1vcpu-1gb}"
        printf '  region = "%s"\n' "${dregion:-nyc3}"
        printf '  image  = "%s"\n' "${dimage:-ubuntu-22-04-x64}"
        printf '}\n\n'
      done
}

_tf_emit_firewalls() {
  local body
  body="$(do_get /firewalls?per_page=200 2>/dev/null)" || return 0
  printf '\n# Cloud Firewalls.\n'
  jq -c '.firewalls[]?' <<<"$body" \
    | while IFS= read -r fw; do
        local fid fname
        fid="$(jq -r '.id'   <<<"$fw")"
        fname="$(jq -r '.name' <<<"$fw")"
        local ln; ln="$(_tf_sanitize_name "${fname}")"
        printf 'resource "digitalocean_firewall" "%s" {\n' "$ln"
        printf '  name = "%s"\n' "$fname"
        printf '  droplet_ids = %s\n' "$(jq -c '.droplet_ids // []' <<<"$fw")"
        printf '  tags = %s\n' "$(jq -c '.tags // []' <<<"$fw")"
        printf '}\n\n'
      done
}

_tf_emit_domains() {
  local body
  body="$(do_get /domains?per_page=200 2>/dev/null)" || return 0
  printf '\n# Domains (DNS only; DigitalOcean managed DNS does NOT support DNSSEC).\n'
  jq -r '.domains[]? | .name' <<<"$body" \
    | while IFS= read -r dname; do
        [[ -z "$dname" ]] && continue
        local ln; ln="$(_tf_sanitize_name "${dname}")"
        printf 'resource "digitalocean_domain" "%s" {\n' "$ln"
        printf '  name = "%s"\n' "$dname"
        printf '}\n\n'
      done
}

_tf_emit_lbs() {
  local body
  body="$(do_get /load_balancers?per_page=200 2>/dev/null)" || return 0
  printf '\n# Load Balancers.\n'
  jq -c '.load_balancers[]?' <<<"$body" \
    | while IFS= read -r lb; do
        local lid lname lregion
        lid="$(jq -r '.id' <<<"$lb")"
        lname="$(jq -r '.name' <<<"$lb")"
        lregion="$(jq -r '.region.slug // ""' <<<"$lb")"
        local ln; ln="$(_tf_sanitize_name "${lname}")"
        printf 'resource "digitalocean_loadbalancer" "%s" {\n' "$ln"
        printf '  name   = "%s"\n' "$lname"
        printf '  region = "%s"\n' "$lregion"
        printf '  redirect_http_to_https = %s\n' "$(jq -r '.redirect_http_to_https // false' <<<"$lb")"
        printf '}\n\n'
      done
}

run_terraform() {
  log_section "terraform export"
  api_check_auth_env || return $?
  local ts; ts="$(date -u +%Y%m%dT%H%M%SZ)"
  local out="${STATE_DIR}/terraform-${ts}.tf"
  log_info "emitting HCL → stdout and ${out}"
  {
    _tf_emit_header
    _tf_emit_droplets
    _tf_emit_firewalls
    _tf_emit_domains
    _tf_emit_lbs
  } | tee "$out"
  log_ok "terraform" "export" "wrote ${out}"
}
