# lib/apply_env.sh — env-var hardening recommendations.
# Idempotent. Reads current state via state_env, then emits CLI command
# stubs for the user to execute. Never types secret values.
# Exports: apply_env [project-id] [environment]

apply_env() {
  local project_id="${1:-}" env_name="${2:-}"
  if [[ -z "$project_id" ]]; then
    project_id="$(api_pick_project 2>/dev/null)" || {
      log_fail "env" "pick" "could not resolve project id"
      return 3
    }
  fi
  if [[ -z "$env_name" ]]; then
    env_name="$(api_pick_environment)"
  fi

  log_section "env hardening for project=${project_id} env=${env_name}"

  # Load digest
  . "$LIB_DIR/state_env.sh"
  local digest
  digest="$(run_state_env "$project_id" "$env_name" digest 2>/dev/null)"
  if [[ -z "$digest" ]] || ! jq -e '.summary' >/dev/null 2>&1 <<<"$digest"; then
    log_fail "env" "read" "could not read env digest"
    return 3
  fi

  local plaintext_count override_count duplicate_count
  plaintext_count="$(jq '.summary.plaintext_secret_warnings // [] | length' <<<"$digest")"
  override_count="$(jq '.summary.reserved_RAILWAY_overrides // [] | length' <<<"$digest")"
  duplicate_count="$(jq '.summary.duplicates_across_services // [] | length' <<<"$digest")"

  if [[ "$plaintext_count" == "0" ]]; then
    log_ok "env" "plaintext-secrets" "no plaintext-secret-shaped values detected (heuristic)."
  else
    log_warn "env" "plaintext-secrets" "${plaintext_count} secret-shaped value(s) appear to be plaintext rather than ${"\${{ shared.* }}"} or ${"\${{ secret.* }}"} references. Recommend moving each to a project-level (shared) variable and referencing it." "https://docs.railway.com/guides/variables"
    jq -r '.summary.plaintext_secret_warnings // [] | .[] | "  - service=\(.service) name=\(.name)  → recommend: railway variables --service \(.service) --set \(.name)='\''<value-via-paste>'\''  (or move to shared:  railway variables --shared --set \(.name)='\''<value>'\'')"' <<<"$digest" >&2
  fi

  if [[ "$override_count" == "0" ]]; then
    log_ok "env" "reserved" "no Railway-reserved env vars are being overridden in user space."
  else
    log_warn "env" "reserved" "${override_count} reserved RAILWAY_*/PORT var(s) are user-set; Railway may overwrite or ignore." "https://docs.railway.com/reference/variables"
    jq -r '.summary.reserved_RAILWAY_overrides // [] | .[] | "  - service=\(.service) name=\(.name)"' <<<"$digest" >&2
  fi

  if [[ "$duplicate_count" == "0" ]]; then
    log_ok "env" "duplicates" "no env-var name duplicated across services (good — refactor opportunities are zero)."
  else
    log_warn "env" "duplicates" "${duplicate_count} env-var name(s) appear in 2+ services. Consider promoting to shared variables and referencing as ${"\${{ shared.NAME }}"}."
    jq -r '.summary.duplicates_across_services // [] | .[] | "  - \(.name) → services: \(.services | join(", "))"' <<<"$digest" >&2
  fi

  # Emit a `templates/env-secret-audit.md` style report file as a stdout block.
  log_subsection "audit report (markdown)"
  printf '\n=== FILE: env-secret-audit.md ===\n=== DIFF ===\n(new file)\n=== CONTENT ===\n'
  printf '# Railway env-var audit — project %s, env %s\n\n' "$project_id" "$env_name"
  printf 'Generated by snitch-railway on %s.\n\n' "$(date -u +%Y-%m-%dT%H:%M:%SZ)"
  printf '## Plaintext-shaped secrets\n\n'
  jq -r '.summary.plaintext_secret_warnings // [] | .[] | "- service `\(.service)` var `\(.name)`"' <<<"$digest"
  printf '\n## Reserved RAILWAY_* overrides\n\n'
  jq -r '.summary.reserved_RAILWAY_overrides // [] | .[] | "- service `\(.service)` var `\(.name)`"' <<<"$digest"
  printf '\n## Duplicate names across services\n\n'
  jq -r '.summary.duplicates_across_services // [] | .[] | "- `\(.name)` in: \(.services | map("`"+.+"`") | join(", "))"' <<<"$digest"
  printf '\n## Recommended remediation order\n\n'
  printf '1. Move each plaintext-shaped secret to a **shared** project variable, then reference as `${{ shared.NAME }}` in each service.\n'
  printf '2. Drop user-set `RAILWAY_*` and `PORT` vars unless you have a specific override reason.\n'
  printf '3. Audit duplicates: same value across services almost always means "promote to shared".\n'
  printf '\n=== END ===\n'
}
