# lib/terraform.sh — emit Terraform AzureRM HCL for current Azure state.
# Read-only. Pins hashicorp/azurerm to ~> 3.0. Output goes to stdout
# AND ${STATE_DIR}/terraform-<ts>.tf.

_tf_sanitize_name() {
  printf '%s' "$1" \
    | tr '[:upper:]' '[:lower:]' \
    | sed -E 's/[^a-z0-9]+/_/g; s/^_+//; s/_+$//; s/^$/x/'
}

_tf_emit_header() {
  cat <<'EOF'
# Auto-generated by snitch-azure. Read-only export of current state.
# AzureRM provider version is pinned because the schema has had breaking
# changes between major versions. Review every resource before terraform apply.

terraform {
  required_providers {
    azurerm = {
      source  = "hashicorp/azurerm"
      version = "~> 3.0"
    }
  }
}

provider "azurerm" {
  features {}
  # subscription_id, tenant_id read from env (ARM_*) or default az login.
}
EOF
}

_tf_emit_storage() {
  local sub_id="$1"
  local body
  body="$(az_run_json storage account list --subscription "$sub_id" 2>/dev/null)" || return 0
  printf '\n# Storage accounts.\n'
  jq -r '.[] | [.name, .resourceGroup, .location, .sku.name, .kind, (.enableHttpsTrafficOnly|tostring), (.minimumTlsVersion // "TLS1_2")] | @tsv' <<<"$body" 2>/dev/null \
    | while IFS=$'\t' read -r name rg loc sku kind https mintls; do
        [[ -z "$name" ]] && continue
        local local_name; local_name="$(_tf_sanitize_name "storage_${name}")"
        printf 'resource "azurerm_storage_account" "%s" {\n' "$local_name"
        printf '  name                     = "%s"\n' "$name"
        printf '  resource_group_name      = "%s"\n' "$rg"
        printf '  location                 = "%s"\n' "$loc"
        printf '  account_tier             = "%s"\n' "${sku%%_*}"
        printf '  account_replication_type = "%s"\n' "${sku##*_}"
        printf '  account_kind             = "%s"\n' "$kind"
        printf '  enable_https_traffic_only = %s\n' "$https"
        printf '  min_tls_version          = "%s"\n' "$mintls"
        printf '}\n\n'
      done
}

_tf_emit_keyvault() {
  local sub_id="$1"
  local body
  body="$(az_run_json keyvault list --subscription "$sub_id" 2>/dev/null)" || return 0
  local tid; tid="$(az_pick_tenant)" || return 0
  printf '\n# Key Vaults.\n'
  jq -r '.[] | [.name, .resourceGroup, .location, .properties.sku.name, (.properties.enableSoftDelete|tostring), (.properties.enablePurgeProtection|tostring), (.properties.enableRbacAuthorization|tostring)] | @tsv' <<<"$body" 2>/dev/null \
    | while IFS=$'\t' read -r name rg loc sku sd pp rbac; do
        [[ -z "$name" ]] && continue
        local local_name; local_name="$(_tf_sanitize_name "kv_${name}")"
        printf 'resource "azurerm_key_vault" "%s" {\n' "$local_name"
        printf '  name                       = "%s"\n' "$name"
        printf '  resource_group_name        = "%s"\n' "$rg"
        printf '  location                   = "%s"\n' "$loc"
        printf '  sku_name                   = "%s"\n' "$sku"
        printf '  tenant_id                  = "%s"\n' "$tid"
        printf '  soft_delete_retention_days = 90\n'
        printf '  purge_protection_enabled   = %s\n' "$pp"
        printf '  enable_rbac_authorization  = %s\n' "$rbac"
        printf '}\n\n'
      done
}

run_terraform() {
  log_section "terraform export"
  auth_verify || return $?
  local ts; ts="$(date -u +%Y%m%dT%H%M%SZ)"
  local sub_id; sub_id="$(az_pick_subscription)" || return 3
  local out="${STATE_DIR}/terraform-${ts}.tf"
  log_info "emitting AzureRM HCL for subscription ${sub_id} → stdout and ${out}"

  {
    _tf_emit_header
    _tf_emit_storage "$sub_id"
    _tf_emit_keyvault "$sub_id"
  } | tee "$out"

  log_ok "terraform" "export" "wrote ${out}"
}
