# lib/terraform.sh — emit Terraform HCL for current Cloudflare state.
# Read-only. Pins the cloudflare/cloudflare provider to ~> 4.0 and emits a
# focused subset of resources: zone settings override, DNS records, and
# non-managed rulesets. Output goes to stdout AND ${STATE_DIR}/terraform-<ts>.tf.
#
# Exports: run_terraform

# _tf_sanitize_name <name>
# Make a string safe to use as a Terraform local-name identifier.
_tf_sanitize_name() {
  printf '%s' "$1" \
    | tr '[:upper:]' '[:lower:]' \
    | sed -E 's/[^a-z0-9]+/_/g; s/^_+//; s/_+$//; s/^$/x/'
}

# _tf_emit_header
_tf_emit_header() {
  cat <<'EOF'
# Auto-generated by snitch-cloudflare. Read-only export of current state.
# Provider version is pinned to ~> 4.0 because the cloudflare/cloudflare
# provider has had breaking schema changes between major versions; pinning
# avoids silent contract changes when you `terraform init` later.
#
# Review every resource before running `terraform apply`. This file is a
# starting point for IaC adoption, not a guarantee of completeness.

terraform {
  required_providers {
    cloudflare = {
      source  = "cloudflare/cloudflare"
      version = "~> 4.0"
    }
  }
}

provider "cloudflare" {
  # api_token is read from CLOUDFLARE_API_TOKEN by default.
}
EOF
}

# _tf_emit_zone_settings <zone_id>
_tf_emit_zone_settings() {
  local zone_id="$1"
  local keys=(
    ssl always_use_https min_tls_version tls_1_3 automatic_https_rewrites
    opportunistic_encryption browser_check security_level challenge_ttl
    brotli http3 0rtt websockets ipv6 email_obfuscation server_side_exclude
    hotlink_protection
  )
  local lines=""
  local k body val
  for k in "${keys[@]}"; do
    body="$(cf_get "/zones/${zone_id}/settings/${k}" 2>/dev/null)" || continue
    val="$(jq -r '.result.value // empty' <<<"$body" 2>/dev/null)"
    [[ -z "$val" ]] && continue
    # On/Off values are strings in the CF API; numbers stay numbers.
    if [[ "$val" =~ ^[0-9]+$ ]]; then
      lines+=$'    '"${k} = ${val}"$'\n'
    else
      lines+=$'    '"${k} = \"${val}\""$'\n'
    fi
  done
  printf '\n# Zone-level settings.\n'
  printf 'resource "cloudflare_zone_settings_override" "this" {\n'
  printf '  zone_id = "%s"\n' "$zone_id"
  printf '  settings {\n'
  printf '%s' "$lines"
  printf '  }\n'
  printf '}\n'
}

# _tf_emit_dns_records <zone_id>
_tf_emit_dns_records() {
  local zone_id="$1"
  local body
  body="$(cf_get "/zones/${zone_id}/dns_records?per_page=500" 2>/dev/null)" || return 0
  printf '\n# DNS records.\n'
  jq -r '.result[]? | [.id, .type, .name, .content, (.ttl|tostring), (.proxied|tostring)] | @tsv' <<<"$body" 2>/dev/null \
    | while IFS=$'\t' read -r rid rtype rname rcontent rttl rproxied; do
        [[ -z "$rid" ]] && continue
        local local_name; local_name="$(_tf_sanitize_name "${rtype}_${rname}")"
        printf 'resource "cloudflare_record" "%s" {\n' "$local_name"
        printf '  zone_id = "%s"\n' "$zone_id"
        printf '  name    = "%s"\n' "$rname"
        printf '  type    = "%s"\n' "$rtype"
        # Quote content for any record type that needs it; CAA/SRV/MX have
        # structured fields but we emit the text content as a fallback.
        printf '  content = "%s"\n' "$(printf '%s' "$rcontent" | sed 's/"/\\"/g')"
        printf '  ttl     = %s\n' "${rttl:-1}"
        printf '  proxied = %s\n' "${rproxied:-false}"
        printf '}\n\n'
      done
}

# _tf_emit_rulesets <zone_id>
_tf_emit_rulesets() {
  local zone_id="$1"
  local body
  body="$(cf_get "/zones/${zone_id}/rulesets" 2>/dev/null)" || return 0
  printf '\n# Custom (non-managed) rulesets.\n'
  jq -c '.result[]? | select(.kind != "managed")' <<<"$body" 2>/dev/null \
    | while IFS= read -r rs; do
        local rs_id rs_name rs_phase rs_kind rs_desc
        rs_id="$(jq -r '.id'   <<<"$rs")"
        rs_name="$(jq -r '.name' <<<"$rs")"
        rs_phase="$(jq -r '.phase' <<<"$rs")"
        rs_kind="$(jq -r '.kind'  <<<"$rs")"
        rs_desc="$(jq -r '.description // ""' <<<"$rs")"
        local local_name; local_name="$(_tf_sanitize_name "${rs_phase}_${rs_id}")"
        printf 'resource "cloudflare_ruleset" "%s" {\n' "$local_name"
        printf '  zone_id     = "%s"\n' "$zone_id"
        printf '  name        = "%s"\n' "$rs_name"
        printf '  description = "%s"\n' "$(printf '%s' "$rs_desc" | sed 's/"/\\"/g')"
        printf '  kind        = "%s"\n' "$rs_kind"
        printf '  phase       = "%s"\n' "$rs_phase"
        # Pull the rules detail.
        local detail; detail="$(cf_get "/zones/${zone_id}/rulesets/${rs_id}" 2>/dev/null)"
        jq -r '.result.rules[]? |
          [(.action // "log"), (.expression // "(true)"), (.description // ""), ((.enabled // true)|tostring)]
          | @tsv' <<<"$detail" 2>/dev/null \
          | while IFS=$'\t' read -r raction rexpr rdesc renabled; do
              [[ -z "$rexpr" ]] && continue
              printf '  rules {\n'
              printf '    action      = "%s"\n' "$raction"
              printf '    expression  = "%s"\n' "$(printf '%s' "$rexpr" | sed 's/"/\\"/g')"
              printf '    description = "%s"\n' "$(printf '%s' "$rdesc" | sed 's/"/\\"/g')"
              printf '    enabled     = %s\n' "$renabled"
              printf '  }\n'
            done
        printf '}\n\n'
      done
}

# run_terraform
run_terraform() {
  log_section "terraform export"
  api_check_auth_env || return $?
  auth_verify || return $?
  local ts; ts="$(date -u +%Y%m%dT%H%M%SZ)"
  local zone_id; zone_id="$(api_pick_zone)" || return 3
  local out="${STATE_DIR}/terraform-${ts}.tf"
  log_info "emitting HCL for zone ${zone_id} → stdout and ${out}"

  {
    _tf_emit_header
    _tf_emit_zone_settings "$zone_id"
    _tf_emit_dns_records   "$zone_id"
    _tf_emit_rulesets      "$zone_id"
  } | tee "$out"

  log_ok "terraform" "export" "wrote ${out}"
}
